theme: jekyll-theme-minimal
title: Shopify Coupon Discount Promo Code
description: Save now on your Shopify account.
#logo: [Location of the logo]
#show_downloads: ["true" or "false" to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]
